client_config_backend: file
client_config:
    client_id: 249003021670-a11vlmosrmtpmpt42o5rucll8p2dh30i.apps.googleusercontent.com
    client_secret: bQJ-PctLeuioWs3VUiMvfTEN

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install